### PR TITLE
Bug e UI 2022 validation error fix 2

### PR DESCRIPTION
**Pull request by adnanakgun**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by Daniel-Lam — APPROVED** [review]
Reviewed and approved; this is based on having reviewed the original PR by @RiteshHMCTS and there is just an extra properties file for Sonar.

**Review by RiteshHMCTS — APPROVED** [review]
looks good

**Review by Mo-Lala84 — APPROVED** [review]
approve

**Pull request merged**
