### PR TITLE
EUI-4112-cve-fix-v2

### PR DESCRIPTION
**Pull request by ishOsw**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4112

### Change description ###
CVEs fix for CCD Toolkits - Build passed on Jenkins but css-what is a vulnerability locally

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by leepavlouhmcts — DISMISSED** [review]

**Review by paul-graham — CHANGES_REQUESTED** [review]
CVE suppressions are pretty-risk free so this looks fine to me. Having said that, I don't think it needs a version increase...

**Review by paul-graham — CHANGES_REQUESTED** [review]
Yeah, this just suppresses the issues. I've just read the ticket and the CVE issues themselves need to be resolved. The command mentioned on the ticket was to show what's been happening to get get through the Jenkins checks _temporarily_ but the versions on the libraries actually need to be sorted now. 😁

**Review by paul-graham — DISMISSED** [review]
Following discussion with @ishOsw, this at least resolves some of the issues reported by the security scanner. There still needs to be work done in the future to sort out the versions once and for all.

**Review by paul-graham — APPROVED** [review]
Just a version change since last I looked. Re-approving.

**Review by paul-graham — APPROVED** [review]

**Pull request closed without merging**
