### PR TITLE
E UI 4402 sscs hidden field data is being cleared

### PR DESCRIPTION
**Pull request by leepavlouhmcts**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4402

### Change description ###
remove 3 properties from directionIssued event

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Mo-Lala84 — DISMISSED** [review]
approved

**Review by RiteshHMCTS — APPROVED** [review]
Approved

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Comment by Daniel-Lam** [comment]
Closing this PR as it is no longer required.

**Pull request closed without merging**
