### PR TITLE
Welsh

### PR DESCRIPTION
**Pull request by johnbenjamin-hmcts**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-5497

### Change description ###
Welsh language 1- MVP

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by udaydenduluri33 — DISMISSED** [review]

**Review by Daniel-Lam — APPROVED** [review]
@DavidJayakumar - PR approved on the basis of having reviewed the last four commits as requested

**Review by connorpgpmcelroy — APPROVED** [review]
Recent commits LGTM

**Comment by johnbenjamin-hmcts** [comment]
This PR is now redundant. Please refer to PR https://github.com/hmcts/ccd-case-ui-toolkit/pull/1523.

**Pull request closed without merging**
