### PR TITLE
Unresponsive and 'laggy' show-hide conditions

### PR DESCRIPTION
**Pull request by kuda1992**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3870

### Change description ###
Show and hide conditions are laggy. So I have reduced the `debounceTime` to 100ms. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Daniel-Lam — APPROVED** [review]
Reviewed your changes @kuda1992 and they look OK to me. You might want to change the `[x ] No` in the description to `[x] No`, as I'm sure @paul-graham will pick this up 😄.

**Review by paul-graham — DISMISSED** [review]
The change looks fine. Is there any chance we can get the FPL team to run their FTs against this PR so we can make sure it resolves their issues?

**Comment by kuda1992** [comment]
> The change looks fine. Is there any chance we can get the FPL team to run their FTs against this PR so we can make sure it resolves their issues?

@paul-graham Does this mean I need to raise a webapp pr first or just a tag will suffice.

**Comment by paul-graham** [comment]
> > The change looks fine. Is there any chance we can get the FPL team to run their FTs against this PR so we can make sure it resolves their issues?
> 
> @paul-graham Does this mean I need to raise a webapp pr first or just a tag will suffice.

Yes, you'll need a PR for **Manage Cases** pointing at a tag-release version of this.

**Review by Mo-Lala84 — APPROVED** [review]
approved

**Review by paul-graham — APPROVED** [review]

**Pull request merged**
