### PR TITLE
EUI-4248 dynamic list and dynamic radio list bugs

### PR DESCRIPTION
**Pull request by adnanakgun**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-4248

### Change description ###

Fixed bugs

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Daniel-Lam — COMMENTED** [review]
@adnanakgun - just one comment raised. Consider also if `read-dynamic-radio-list-field.component.spec.ts` needs any additional tests for when `formatted_value` is empty/non-empty.

**Comment by adnanakgun** [comment]
> @adnanakgun - just one comment raised. Consider also if `read-dynamic-radio-list-field.component.spec.ts` needs any additional tests for when `formatted_value` is empty/non-empty.

@Daniel-Lam can re-review please, I've made the requested changes.

**Review by Daniel-Lam — APPROVED** [review]
@adnanakgun - thanks for adding the additional `null` / `undefined` check and extra unit tests. Approved.

**Review by RiteshHMCTS — APPROVED** [review]

**Review by Mo-Lala84 — APPROVED** [review]
approoved

**Pull request merged**
