### PR TITLE
Remove old css and icon for accessibility contrast

### PR DESCRIPTION
**Pull request by paulhowes-HMCTS**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-2032

### Change description ###
Remove css and icon from the demo app for accessibility and GDS compliancy

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by paul-graham — APPROVED** [review]
All looks good to me. No version number needed for a tidy-up on a page that doesn't even get compiled in. However, it's good to include the ticket in `RELEASE-NOTES.md` so we can track it.

Approved. 👍

**Review by Daniel-Lam — APPROVED** [review]
@paulhowes-HMCTS - reviewed, including @paul-graham's comment... approved

**Comment by paulhowes-HMCTS** [comment]
Closing PR as it involved a breaking change which was never merged into release. Superseded by a latter change.

**Comment by paulhowes-HMCTS** [comment]
Now closing. See comment on https://tools.hmcts.net/jira/browse/EUI-2032.

**Pull request closed without merging**
